name: amazon_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cloud_firestore: ^3.4.8
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8

  cupertino_icons: ^1.0.5
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  rating_dialog: ^2.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
