// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJKhDHp1CjhM22frXvzquK6H7gzUfnM0c',
    appId: '1:730032909619:web:f63120b64c29a2dff66246',
    messagingSenderId: '730032909619',
    projectId: 'clone-9379a',
    authDomain: 'clone-9379a.firebaseapp.com',
    storageBucket: 'clone-9379a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMFUtMpq3L2RoeUiR5oha_r2BYpkfNN5g',
    appId: '1:730032909619:android:d586b237c6574d15f66246',
    messagingSenderId: '730032909619',
    projectId: 'clone-9379a',
    storageBucket: 'clone-9379a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiuMpn-RyYSJVrydm686jR9JhW0fXEKW8',
    appId: '1:730032909619:ios:0fa5d816586804b4f66246',
    messagingSenderId: '730032909619',
    projectId: 'clone-9379a',
    storageBucket: 'clone-9379a.appspot.com',
    iosClientId: '730032909619-cttiatjb0ease38jp83qmiipg7gmi2j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiuMpn-RyYSJVrydm686jR9JhW0fXEKW8',
    appId: '1:730032909619:ios:0fa5d816586804b4f66246',
    messagingSenderId: '730032909619',
    projectId: 'clone-9379a',
    storageBucket: 'clone-9379a.appspot.com',
    iosClientId: '730032909619-cttiatjb0ease38jp83qmiipg7gmi2j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonClone',
  );
}
